# Generated by Django 5.0.4 on 2024-05-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='category_updated',
        ),
        migrations.AddField(
            model_name='runner',
            name='nickname',
            field=models.CharField(max_length=12, null=True, verbose_name='никнейм'),
        ),
    ]
