# Generated by Django 5.0.4 on 2024-05-06 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_runner_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='family',
            field=models.ManyToManyField(related_name='family_users', to=settings.AUTH_USER_MODEL, verbose_name='выберите участников'),
        ),
    ]
