# Generated by Django 5.0.4 on 2024-05-16 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_family_runner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Семейное участие', 'verbose_name_plural': 'Семейное участие'},
        ),
        migrations.AlterField(
            model_name='family',
            name='runner_family',
            field=models.ManyToManyField(blank=True, related_name='runners_family', to=settings.AUTH_USER_MODEL),
        ),
    ]
